# Generated by Django 5.2.8 on 2025-12-03 14:41

import apps.cars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, help_text='Unique car license plate number (auto-normalized to uppercase, spaces removed)', max_length=20, unique=True)),
                ('make', models.CharField(blank=True, default='', help_text='Car manufacturer (e.g., Toyota, BMW)', max_length=100)),
                ('model', models.CharField(blank=True, default='', help_text='Car model (e.g., Camry, X5)', max_length=100)),
                ('year', models.IntegerField(blank=True, help_text='Manufacturing year (e.g., 2020)', null=True, validators=[apps.cars.models.validate_car_year])),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number (17 characters)', max_length=17, null=True, unique=True)),
                ('color', models.CharField(blank=True, help_text='Car color', max_length=50, null=True)),
                ('mileage', models.IntegerField(default=0, help_text='Current mileage in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when car was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when car info was last updated')),
                ('customer', models.ForeignKey(help_text='Car owner', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_plate'], name='cars_license_e2acb7_idx'), models.Index(fields=['vin'], name='cars_vin_1eb7a8_idx'), models.Index(fields=['customer', '-created_at'], name='cars_custome_752351_idx')],
                'unique_together': {('customer', 'license_plate')},
            },
        ),
    ]
