# Generated by Django 5.2.8 on 2026-02-27 23:47

import apps.cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(
                default=0,
                help_text='Current mileage in kilometers',
                validators=[apps.cars.models.validate_car_mileage],
            ),
        ),
    ]
