# Generated by Django 5.2.8 on 2025-12-03 14:41

import apps.customers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255, validators=[apps.customers.models.validate_customer_name])),
                ('email', models.EmailField(blank=True, help_text="Customer's email address (unique)", max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text="Customer's address", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when customer was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when customer info was last updated')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='customers_email_92e882_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['name'], name='customers_name_25d5e3_idx'), models.Index(fields=['created_at'], name='customers_created_c63477_idx')],
            },
        ),
    ]
