# Generated by Django 5.2.8 on 2025-12-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Chat session title', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chat session is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the chat session started')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the chat session was last updated')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the chat session was closed', null=True)),
                ('session_metadata', models.JSONField(blank=True, default=dict, help_text='Session metadata (model used, tokens consumed, etc.)')),
                ('complaint', models.ForeignKey(help_text='The complaint this chat is about', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant (AI Mechanic)'), ('system', 'System')], help_text='Message sender role', max_length=20)),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata')),
                ('session', models.ForeignKey(help_text='The chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['complaint', '-created_at'], name='chat_sessio_complai_04da1d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_active'], name='chat_sessio_is_acti_13a9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-updated_at'], name='chat_sessio_updated_5baaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_597c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chat_messag_role_ddd811_idx'),
        ),
    ]
