# Generated by Codex on 2026-02-27

from django.db import migrations, models
from django.utils import timezone


def deduplicate_active_sessions(apps, schema_editor):
    ChatSession = apps.get_model('chat', 'ChatSession')
    duplicate_groups = (
        ChatSession.objects
        .filter(is_active=True)
        .values('complaint_id')
        .annotate(active_count=models.Count('id'))
        .filter(active_count__gt=1)
    )

    for group in duplicate_groups.iterator():
        sessions = list(
            ChatSession.objects
            .filter(complaint_id=group['complaint_id'], is_active=True)
            .order_by('-updated_at', '-id')
        )
        if not sessions:
            continue

        keeper = sessions[0]
        if keeper.closed_at is not None:
            keeper.closed_at = None
            keeper.save(update_fields=['closed_at'])

        for session in sessions[1:]:
            session.is_active = False
            session.closed_at = session.closed_at or session.updated_at or timezone.now()
            session.save(update_fields=['is_active', 'closed_at'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(deduplicate_active_sessions, noop_reverse),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=('complaint',),
                name='unique_active_chat_session_per_complaint',
            ),
        ),
    ]
