# Generated by Django 5.2.8 on 2025-12-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(help_text='Original complaint text from customer')),
                ('cleaned_text', models.TextField(blank=True, help_text='Pre-processed text used for ML prediction')),
                ('predicted_category', models.CharField(blank=True, choices=[('advanced_safety', 'Advanced Safety'), ('airbags_seatbelts', 'Airbags & Seatbelts'), ('brakes_safety', 'Brakes & Safety'), ('electrical_system', 'Electrical System'), ('engine', 'Engine'), ('fuel_system', 'Fuel System'), ('power_train', 'Power Train'), ('steering_suspension', 'Steering & Suspension'), ('structure_body', 'Structure & Body'), ('visibility_lighting', 'Visibility & Lighting'), ('wheels_tires', 'Wheels & Tires')], help_text='ML-predicted category of the issue', max_length=50, null=True)),
                ('prediction_confidence', models.FloatField(default=0.0, help_text='Confidence score of the ML prediction (0-1)')),
                ('crash', models.BooleanField(default=False, help_text='Whether this complaint involves a crash')),
                ('fire', models.BooleanField(default=False, help_text='Whether this complaint involves a fire')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of complaint resolution', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Notes about complaint resolution or actions taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when complaint was filed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when complaint was last updated')),
                ('car', models.ForeignKey(help_text='Car this complaint is about', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='cars.car')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', '-created_at'], name='complaints_car_id_27e249_idx'), models.Index(fields=['predicted_category'], name='complaints_predict_87bcb5_idx'), models.Index(fields=['status'], name='complaints_status_3d57ee_idx'), models.Index(fields=['crash'], name='complaints_crash_287917_idx'), models.Index(fields=['fire'], name='complaints_fire_5a74b4_idx'), models.Index(fields=['-created_at'], name='complaints_created_0cc0c9_idx')],
            },
        ),
    ]
