# Generated by Django 5.2.8 on 2025-12-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='complaint_docs/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(help_text='File type (pdf, image, etc.)', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_analyzed', models.BooleanField(default=False, help_text='Whether the document has been processed by RAG')),
                ('analysis_error', models.TextField(blank=True, help_text='Error message if analysis failed', null=True)),
                ('complaint', models.ForeignKey(help_text='Complaint this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='complaints.complaint')),
            ],
            options={
                'db_table': 'complaint_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
