# Generated by Django 5.2.8 on 2025-12-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image File'), ('text', 'Text File')], max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('indexed', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('index_error', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Metadata',
                'verbose_name_plural': 'Document Metadata',
                'db_table': 'document_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100, unique=True)),
                ('chunk_type', models.CharField(choices=[('text', 'Text Content'), ('image', 'Image'), ('table', 'Table')], max_length=20)),
                ('page_number', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('text_vector_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_vector_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ml_models.documentmetadata')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'document_chunks',
                'ordering': ['document', 'page_number'],
            },
        ),
    ]
